Fri Dec 06 17:21:45 EST 2019 : Apache Derby Network Server - 10.8.1.2 - (1095077) started and ready to accept connections on port 1527
----------------------------------------------------------------
Fri Dec 06 17:21:45 EST 2019:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.8.1.2 - (1095077): instance a816c00e-016e-dd4d-fb1c-000053d219e8 
on database directory C:\Users\Bret\Documents\NetBeans Projects\inventoryApp\netbeans-derby\InventoryManagementSystem  with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/C:/Users/Bret/Documents/NetBeans%20Projects/inventoryApp/glassfish/javadb/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_231-b11
user.dir=C:\Users\Bret\Documents\NetBeans Projects\inventoryApp\glassfish\javadb
derby.system.home=C:\Users\Bret\Documents\NetBeans Projects\inventoryApp\netbeans-derby
Database Class Loader started - derby.database.classpath=''
Fri Dec 06 17:21:46 EST 2019 Thread[DRDAConnThread_3,5,main] (XID = 1131), (SESSIONID = 0), (DATABASE = InventoryManagementSystem), (DRDAID = {1}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: java.sql.SQLException: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 19 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Fri Dec 06 17:21:46 EST 2019 Thread[DRDAConnThread_3,5,main] (DATABASE = InventoryManagementSystem), (DRDAID = {1}), Connection authentication failure occurred.  Reason: Invalid authentication..
----------------------------------------------------------------
Fri Dec 06 17:22:25 EST 2019:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.8.1.2 - (1095077): instance 888c4022-016e-dd4d-fb1c-000053d219e8 
on database directory C:\Users\Bret\Documents\NetBeans Projects\inventoryApp\netbeans-derby\sample  with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/C:/Users/Bret/Documents/NetBeans%20Projects/inventoryApp/glassfish/javadb/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_231-b11
user.dir=C:\Users\Bret\Documents\NetBeans Projects\inventoryApp\glassfish\javadb
derby.system.home=C:\Users\Bret\Documents\NetBeans Projects\inventoryApp\netbeans-derby
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Fri Dec 06 20:45:13 EST 2019: Shutting down Derby engine
----------------------------------------------------------------
Fri Dec 06 20:45:13 EST 2019:
Shutting down instance 888c4022-016e-dd4d-fb1c-000053d219e8 on database directory C:\Users\Bret\Documents\NetBeans Projects\inventoryApp\netbeans-derby\sample with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
----------------------------------------------------------------
Fri Dec 06 20:45:13 EST 2019:
Shutting down instance a816c00e-016e-dd4d-fb1c-000053d219e8 on database directory C:\Users\Bret\Documents\NetBeans Projects\inventoryApp\netbeans-derby\InventoryManagementSystem with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
----------------------------------------------------------------
